GamesStore/src/GameStore/Controllers/GameController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.IO;
using GameStore.Request;
using System;
using GameStore.Response;

namespace GameStore.Controllers
{
    public class GameController : Controller
    {
        private readonly IHostingEnvironment _environment;

        public GameController(IHostingEnvironment environment)
        {
            _environment = environment;
        }

        [HttpGet]
        public IActionResult AddGame()
        {
            if (ViewBag.Game == null)
            {
                ViewBag.Game = new GameRequest() { Price = 0,Name=" ",Category = string.Empty,Description =" ",Image = " "};
                

            }
            return View();
        }

        [HttpGet]
        public IActionResult Order()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GameProfile()
        {
            var id = Convert.ToInt32(Request.Query["gameId"]);
            var gameResponse = new CurrentGameResponse
            {
                GameId = id
            };
            return View(gameResponse);
        }

        [HttpGet]
        public IActionResult OwnGameList()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EditOrDeleteGame()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ShowGame()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Bucket()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddGame(ICollection<IFormFile> files, string gameName, string gameDescription, string gamePrice)
        {
            GameRequest request = new GameRequest();
            request.Description = gameDescription;
            request.Name = gameName;
            request.Price = Convert.ToInt32(gamePrice);
            

            var uploads = _environment.WebRootPath;
            uploads += "\\images";

            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
                    {
                         request.Image = file.FileName;
                        await file.CopyToAsync(fileStream);
                    }
                }
            }
            ViewBag.Game = request;
            return View();
        }
    }
}

GamesStore/src/GameStore/Views/Shared/_Layout.cshtml
@using System.Threading.Tasks
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity
@using GameStore.Infrastructure.Wrappers

@inject SignInManegerWrapper SignInManager





<!DOCTYPE html>
<html ng-app="GameStoreApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/AngularJS-Toaster/toaster.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        
        <link href="~/lib/semantic/dist/semantic.css" rel="stylesheet" />
        <script src="~/lib/semantic/examples/assets/library/jquery.min.js"></script>
        <script src="~/lib/semantic/dist/semantic.js"></script>
        <!--- Example Libs -->
        <link rel="stylesheet" type="text/css" href="~/lib/semantic/dist/components/popup.css">


    </environment>
    <!--- Component JS -->
    <script type="text/javascript" src="~/lib/semantic/dist/components/transition.js"></script>
    <script type="text/javascript" src="~/lib/semantic/dist/components/dropdown.js"></script>
    <script src="~/lib/semantic/dist/components/sidebar.js"></script>
    <script src="~/lib/semantic/dist/components/transition.js"></script>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
  
    <div class="ui top fixed menu">
        <div class="item">
            <img src="~/images/icon.png" />
        </div>
        @if (User.IsInRole("Administrator"))
            {
            <a class="item" asp-controller="Home" asp-action="Index">Adminpanel</a>
            <a class="item" asp-controller="Game" asp-action="AddGame">Add Game</a>
            <a class="item" asp-controller="Game" asp-action="EditOrDeleteGame">Edit Game</a>
            <a class="item" asp-controller="Game" asp-action="Order">Show All Order</a>

        }
        else
        {
            @if (User.IsInRole("Customer"))
                {

                <a class="item" asp-controller="Game" asp-action="ShowGame">Game</a>
                <a class="item" asp-controller="Game" asp-action="Bucket">Bucket</a>
                <a class="item" asp-controller="Game" asp-action="Order">Show My Order</a>
                <a class="item" asp-controller="Game" asp-action="OwnGameList">Own Game List</a>
            }
        }
        <div class="right menu">

            <div class="item">
                @if (SignInManager.IsSignedIn(User))
                {
                    <form asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
                        <button type="submit" class="ui primary button">LogOff</button>
                    </form>
                }
                else
                {
                    <a class="ui primary button" asp-controller="Account" asp-action="Login">LogIn</a>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
      
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>


        <script src="~/lib/angular/angular.js"></script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/GameStoreApp.js"></script>
        <script src="~/lib/angular-animate/angular-animate.js"></script>
        <script src="~/lib/AngularJS-Toaster/toaster.js"></script>
        <script src="~/js/Services/AlertService.js"></script>
     
 
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("scripts", required: false)

</body>
</html>